image: ruby:2.5.1
stages:
  - deploy

before_script:
  - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
  - eval $(ssh-agent -s)
  - ssh-add <(echo -e “$SSH_PRIVATE_KEY”)

#    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
#    - eval $(ssh-agent -s)
#    - ssh-add <(echo -e "$SSH_PRIVATE_KEY")
#    - gem install bundle
#    - bundle install

deploy:
  environment: production
#  environment: staging
  stage: deploy
#  tags:
#    - online-node
  only:
    - master
  script:
    - gem install capistrano
    - cap production deploy
#    - gem install bundle
#    - bundle install
#    - bundle exec cap production deploy